name: Deploy ListList API

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy-api.yml'
      - 'ListList.Api/**' 
      - 'ListList.Data/**' 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout API code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout Auth repo
        uses: actions/checkout@v3
        with:
          repository: michaelasanchez/auth
          path: ./auth
          token: ${{ secrets.AUTH_REPO_PAT }}
          ref: master
          
      - name: Build Auth
        run: dotnet build ./auth/auth/Auth.csproj --configuration Release

      - name: Pack Auth
        run: dotnet pack ./auth/auth/Auth.csproj --configuration Release -o ./auth/nupkgs

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        shell: bash
        run: dotnet restore ./ListList.Api/ListList.Api.csproj --configfile ./nuget.release.config

      - name: Build project
        run: dotnet build ./ListList.Api/ListList.Api.csproj --configuration Release

      - name: Publish project
        run: dotnet publish ./ListList.Api/ListList.Api.csproj `
             --configuration Release `
             /p:WebPublishMethod=Package `
             /p:PackageAsSingleFile=true `
             /p:SkipInvalidConfigurations=true `
             /p:PackageLocation=./publish/api.zip
             
      - name: Upload published API
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download published API
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: ./publish

      - name: Deploy API to IIS
        uses: ChristopheLav/iis-deploy@v1
        with:
          website-name: ${{ secrets.DEPLOY_SITE_API }}
          msdeploy-service-url: ${{ secrets.DEPLOY_PUBLISH_URL }}
          msdeploy-username: ${{ secrets.DEPLOY_USERNAME }}
          msdeploy-password: ${{ secrets.DEPLOY_PASSWORD }}
          source-path: ./publish/api.zip

